Repository Workiva/opentelemetry-dart, pull requests merged in 2023-10, with the labels that each got.

#123 O11Y-3138: Remove Deprecated SDK exports for SpanContext, TraceState, and W3cTraceContextPropagator.
  lib/sdk.dart
  lib/src/sdk/trace/propagation/w3c_trace_context_propagator.dart
  lib/src/sdk/trace/sampling/always_on_sampler.dart
  lib/src/sdk/trace/span_context.dart
  lib/src/sdk/trace/trace_state.dart
  test/integration/sdk/propagation/w3c_trace_context_propagator_test.dart
  test/integration/sdk/span_context_test.dart
  test/unit/api/span_context_test.dart
  test/unit/sdk/propagation/w3c_trace_context_propagator_test.dart
  test/unit/sdk/span_context_test.dart
  test/unit/sdk/trace_state_test.dart
Labels: semver: Major

#124 O11Y-3138: Improve Adherence to Specification
  lib/api.dart
  lib/sdk.dart
  lib/src/api/open_telemetry.dart
  lib/src/api/trace/nonrecording_span.dart
  lib/src/api/trace/span.dart
  lib/src/sdk/platforms/web/trace/web_tracer_provider.dart
  lib/src/sdk/trace/span.dart
  lib/src/sdk/trace/tracer.dart
  lib/src/sdk/trace/tracer_provider.dart
  test/integration/api/propagation/w3c_trace_context_propagator_test.dart
  test/integration/open_telemetry_test.dart
  test/integration/sdk/span_test.dart
  test/integration/sdk/tracer_test.dart
  test/unit/api/context_test.dart
  test/unit/api/propagation/w3c_trace_context_propagator_test.dart
  test/unit/sdk/exporters/collector_exporter_test.dart
  test/unit/sdk/exporters/console_exporter_test.dart
  test/unit/sdk/platforms/web/web_time_provider_test.dart
  test/unit/sdk/sampling/always_off_sampler_test.dart
  test/unit/sdk/sampling/always_on_sampler_test.dart
  test/unit/sdk/sampling/parent_based_sampler_test.dart
  test/unit/sdk/span_limits_test.dart
  test/unit/sdk/span_test.dart
Labels: semver: Major

#126 O11Y-3369: Migrate opentelemetry-dart to GHA
  .github/dependabot.yaml
  .github/workflows/dart_ci.yaml
  .github/workflows/publish.yaml
  Dockerfile
  skynet.yaml
Labels: Merge Requirements Unmet, semver: Patch

#131 Dart 2.19
  .github/workflows/dart_ci.yaml
Labels: Merge Requirements Met, RM Ready, semver: Patch

#134 O11Y-3369: Migrate opentelemetry-dart to GHA
  .github/workflows/publish.yaml
Labels: Merge Requirements Unmet, RM Ready
